name: EconomyAirportNukkitJapanVersion
main: economyairport.nukkitjapanversion.economyairportnukkitjapanversion.Main
version: 1.0.0
author: gamesukimanIRS
api: ["1.0.0"]
commands:
  setwarp:
    description: 新規ワープを作成
    usage: "/setwarp WarpName"
    permission: setwarp.cmd

  delwarp:
    description: ワープを削除
    usage: "/delwarp WarpName"
    permission: delwarp.cmd
    
  permissons:
    setwarp.cmd:
      default: op
    delwarp.cmd:
      default: op