name: EconomyAirportNukkitJapanVersion
main: gamesukimanirs.economyairportnukkitjapanversion.Main
version: 1.0.0
author: gamesukimanIRS
api: ["1.0.0"]
commands:
  setwarp:
    description: 新規ワープを作成
    usage: "/setwarp WarpName"
    permission: setwarp.cmd
    default: op

  delwarp:
    description: ワープを削除
    usage: "/delwarp WarpName"
    permission: delwarp.cmd
    default: op